=== ImCrispeh/Movie-Store-Web-Service/web/WEB-INF/users.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://uts/wsd/oms"
           xmlns="http://uts/wsd/oms"
           elementFormDefault="qualified">

    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="firstName" type="name"/>
                            <xs:element name="lastName" type="name"/>
                            <xs:element name="email" type="email"/>
                            <xs:element name="password" type="password"/>
                            <xs:element name="phoneNo" type="phoneNo"/>
                            <xs:element name="address" type="xs:string"/>
                            <xs:element name="city" type="city"/>
                            <xs:element name="state" type="state"/>
                            <xs:element name="postCode" type="postCode"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ImCrispeh/Movie-Store-Web-Service/web/WEB-INF/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users
    xmlns="http://uts/wsd/oms"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://uts/wsd/oms users.xsd">>
    <user>
        <firstName>Ryan</firstName>
        <lastName>Heise</lastName>
        <email>ryan@ryanheise.com</email>
        <password>blahblah</password>
        <phoneNo>12345678</phoneNo>
        <address>123 fake st</address>
        <city>sydney</city>
        <state>NSW</state>
        <postcode>2000</postcode>
    </user>
    <user>
        <firstName>Joe</firstName>
        <lastName>Bloggs</lastName>
        <email>joe@bloggs.com</email>
        <password>foobar</password>
        <phoneNo>12345678</phoneNo>
        <address>123 fake st</address>
        <city>sydney</city>
        <state>NSW</state>
        <postcode>2000</postcode>
    </user>
</users>
